apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topic-script
data:
  create-topics.sh: |
    #!/bin/bash
    KAFKA_BROKER="kafka:9092"
    TOPICS=("raft-logs" "store-logs")
    RETENTION_MS="1800000"
    PARTITIONS=3
    REPLICATION_FACTOR=1

    echo "Waiting for Kafka at $KAFKA_BROKER..."
    for i in {1..30}; do
      kafka-topics --list --bootstrap-server "$KAFKA_BROKER" &>/dev/null && break
      sleep 2
    done

    for TOPIC in "${TOPICS[@]}"; do
      if kafka-topics --list --bootstrap-server "$KAFKA_BROKER" | grep -qw "$TOPIC"; then
        echo "Topic '$TOPIC' exists."
      else
        kafka-topics --create --topic "$TOPIC" --bootstrap-server "$KAFKA_BROKER" --partitions "$PARTITIONS" --replication-factor "$REPLICATION_FACTOR" --config "retention.ms=$RETENTION_MS"
      fi
    done
