apiVersion: v1
kind: Service
metadata:
  name: raft-node
  labels:
    app: raft-node
spec:
  clusterIP: None  # Headless service
  selector:
    app: raft-node
  ports:
    - name: http
      port: 8000
      targetPort: 8000
